name: community_page
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Add dependencies for your project
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Define the assets directory
  assets:
    - assets/data/notices.json  # For JSON and other data files
    - assets/data/event.json
    - assets/images/
    - assets/images/landmark.jpeg
    - assets/icons/notification.svg
    - assets/icons/

  # If you are using SVG icons, make sure to include the flutter_svg package as a dependency

